name: Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Vim
      run: sudo apt-get update && sudo apt-get install -y vim
    
    - name: Run integration test
      run: ./tests/test_log.sh ${{ github.workspace }}
