name: Integration Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Vim
      run: sudo apt-get update && sudo apt-get install -y vim
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Flask
      run: pip install flask
    
    - name: Run log integration test
      run: ./tests/test_log.sh ${{ github.workspace }}
    
    - name: Run QQ integration test
      run: ./tests/test_q.sh ${{ github.workspace }}

    - name: Run QQ integration test
      run: ./tests/test_qq.sh ${{ github.workspace }}

    - name: Run QQ integration test
      run: ./tests/test_qq_list.sh ${{ github.workspace }}

    - name: Run QQ integration test
      run: ./tests/test_q_new.sh ${{ github.workspace }}

    - name: Run QQ integration test
      run: ./tests/test_q_second.sh ${{ github.workspace }}
