name: Local Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Vim
      run: sudo apt-get update && sudo apt-get install -y vim

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Flask
      run: pip install flask
    
    - name: Install themis
      uses: actions/checkout@v2
      with:
        repository: thinca/vim-themis
        path: vim-themis
    
    - name: Run all integration tests
      run: ./vim-themis/bin/themis ./tests/local
