name: Integration Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Vim
      run: sudo apt-get update && sudo apt-get install -y vim

    - name: Install NeoVim
      run: sudo apt-get update && sudo apt-get install -y neovim
    
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Flask
      run: pip install flask
    
    - name: Run all integration tests
      run: VIMQQ_VERBOSE=1 ./tests/run_all.sh ${{ github.workspace }}
    
    - name: Run all integration tests with neovim
      run: VIMQQ_VERBOSE=1 VIMQQ_VIM_BINARY=nvim  ./tests/run_all.sh ${{ github.workspace }}
